django_app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

from accounts.views import UserSignupView


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", UserSignupView.as_view(), name="signup"),
    path("tang/", include("tang.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

django_app/tang/urls.py
from django.urls import path, register_converter

from . import views
# from . import converters


# register_converter(converters.HangulSlugConverter, 'herb_slug')


app_name = "tang"
urlpatterns = [
    path("recipes/", views.recipe_list, name="recipe_list"),
    path("recipes/<str:slug>/", views.recipe_detail, name="recipe_detail"),
    path("herbs/", views.herb_list, name="herb_list"),
    path("herbs/<str:slug>/", views.herb_detail, name="herb_detail"),   
]

django_app/accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField("이메일", unique=True)
    cell_phone = models.CharField("휴대폰", max_length=20, null=False, blank=False)
    name = models.CharField("이름", max_length=30, null=False, blank=False)
    date_joined = models.DateTimeField("가입일", auto_now_add=True)
    is_staff = models.BooleanField("운영진", default=False)
    is_active = models.BooleanField("이용가능여부", default=False)
    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = verbose_name_plural = "원장님"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    license_number = models.PositiveSmallIntegerField(
        "면허번호", unique=True, null=False, blank=False
    )
    license_image = models.ImageField(upload_to="license", blank=False)

    class Meta:
        verbose_name = verbose_name_plural = "원장님 정보"


class Business(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="business")
    name = models.CharField("한의원명", max_length=30, null=False, blank=False)
    address = models.CharField("주소", max_length=100, null=False, blank=False)
    business_phone = models.CharField("전화번호", max_length=20, null=False, blank=False)
    cell_phone = models.CharField("휴대폰", max_length=20, null=False, blank=False)
    fax = models.CharField("팩스", max_length=20, null=False, blank=False)
    business_number = models.PositiveSmallIntegerField(
        "사업자번호", unique=True, null=False, blank=False
    )
    business_image = models.ImageField("사업자등록증", upload_to="business", blank=False)

    class Meta:
        verbose_name = verbose_name_plural = "한의원 정보"


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="address")
    reciever_name = models.CharField("받는 사람", max_length=30, null=False, blank=False)
    address = models.CharField("주소", max_length=100, null=False, blank=False)
    address_detail = models.CharField("상세주소", max_length=100, null=False, blank=False)
    cell_phone = models.CharField("휴대폰", max_length=20, null=False, blank=False)
    is_default = models.BooleanField("기본배송지", default=False)

    class Meta:
        verbose_name = verbose_name_plural = "배송지 정보"

django_app/delivery/models.py
from django.db import models

# Create your models here.
class Address(models.Model):
    # user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    address_detail = models.CharField(max_length=100)
    is_default = models.BooleanField(default=False)
    contact = models.ForeignKey("Contact", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.address} {self.address_detail}"

    class Meta:
        verbose_name_plural = "주소"


class Contact(models.Model):
    contact = models.CharField(
        max_length=20,
        validators=[],
    )
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.contact
    
    class Meta:
        verbose_name_plural = "연락처"

django_app/product/models.py
from django.db import models

# Create your models here.

django_app/tang/models.py
import math
from typing import Collection, Optional

from django.db import models
from django.shortcuts import resolve_url


# Create your models here.
class Herb(models.Model):
    name = models.CharField(max_length=10)
    slug = models.SlugField(allow_unicode=True, unique=True, null=False, blank=False)
    buy_price = models.PositiveSmallIntegerField(default=1)
    buy_unit = models.PositiveSmallIntegerField(default=600)
    margin = models.PositiveSmallIntegerField(default=30)

    def __str__(self):
        return self.name

    @property
    def price(self):
        return math.ceil(self.buy_price / self.buy_unit * (1 + self.margin / 100))

    # TODO 하드코딩 개선하기 -> test_herb_get_absolute_url 개선하기
    def get_absolute_url(self):
        return f"/tang/herbs/{self.slug}/"

    def save(self, *args, **kwargs):
        self.slug = self.name
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "약재"


class Recipe(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(allow_unicode=True, unique=True, null=False, blank=False)
    herbs = models.ManyToManyField(Herb, related_name="recipe", through="RecipeHerb")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = self.name
        super().save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = "처방전"


class RecipeHerb(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    herb = models.ForeignKey(Herb, on_delete=models.CASCADE)
    herb_amount = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"{self.herb} {self.herb_amount}g"

    class Meta:
        verbose_name_plural = "처방전 구성"
        constraints = [
            models.UniqueConstraint(
                fields=["recipe", "herb"], name="unique_recipe_herb"
            )
        ]

django_app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


class CustomAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))


class UserSignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

django_app/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserSignupForm


class UserSignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = UserSignupForm
    success_url = reverse_lazy("index")

django_app/delivery/views.py
from django.shortcuts import render

# Create your views here.

django_app/product/views.py
from django.shortcuts import render

# Create your views here.

django_app/tang/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Herb, Recipe


class RecipeListView(ListView):
    model = Recipe

recipe_list = RecipeListView.as_view()


class RecipeDetailView(DetailView):
    model = Recipe

recipe_detail = RecipeDetailView.as_view()


class HerbListView(ListView):
    model = Herb

herb_list = HerbListView.as_view()


class HerbDetailView(DetailView):
    model = Herb

herb_detail = HerbDetailView.as_view()

django_app/templates/cart.html
<h2>장바구니</h2>
<ul>

    <li><label><input type="checkbox" name="cash" value="cash">환자명, 처방명, 가격</label></li>
    <li><label><input type="checkbox" name="cash" value="cash">환자명, 처방명, 가격</label></li>
    <li><label><input type="checkbox" name="cash" value="cash">환자명, 처방명, 가격</label></li>
    <li><label><input type="checkbox" name="cash" value="cash">환자명, 처방명, 가격</label></li>
</ul>
<form action="order_list.html">
    <fieldset>
        <legend>배송정보</legend>
        <label for="receiver">받는사람</label>
        <input type="text" name="receiver" id="receiver"><br>
        <label for="address">주소</label>
        <input type="text" name="address" id="address"><br>
        <label for="전화번호">전화번호</label>
        <input type="tel" name="tel" id="tel">
    </fieldset>
    <fieldset>
        <legend>결제금액</legend>
        <label for="delivery">배송료</label>
        <input type="number" name="price" id="price" value="5000" readonly><br>
        <label for="delivery">총 결제금액</label>
        <input type="number" name="price" id="price" value="55400" readonly>
    </fieldset>
    <fieldset>
        <legend>결제정보</legend>
        <label><input type="radio" name="checkout" value="card" checked>카드</label>
        <label><input type="radio" name="checkout" value="cash">현금</label>
    </fieldset>
    <button type="submit">결제하기</button>
</form>

django_app/templates/form.html
<h2>처방하기</h2>
<form action="cart.html">
    <fieldset>
        <legend>환자정보</legend>
        <label for="patient">환자명</label>
        <input type="text" name="patient" id="patient">
    </fieldset>
    <fieldset>
        <legend>처방정보</legend>
        <label for="tang">처방명</label>
        <input type="text" name="patient-name" id="patient-name"><br>
        <input type="text" name="herb-1" list="herb-list">
        <input type="number" name="herb-1-q" id="herb-1-q">g<br>
    
        <input type="text" name="herb-2" list="herb-list">
        <input type="number" name="herb-2-q" id="herb-2-q">g<br>
    
        <input type="text" name="herb-3" list="herb-list">
        <input type="number" name="herb-3-q" id="herb-3-q">g<br>
        <input type="text" name="herb-4" list="herb-list">
        <input type="number" name="herb-4-q" id="herb-4-q">g<br>
    
        <datalist id="herb-list">
            <option value="인삼"/>
            <option value="백출"/>
            <option value="복령"/>
            <option value="감초"/>
            <option value="지황"/>
            <option value="당귀"/>
            <option value="작약"/>
            <option value="천궁"/>
        </datalist>
        <div>
            <input type="number" name="chub" id="chub">
            <label for="chub">첩</label><br>
            <input type="number" name="pack" id="pack">
            <label for="pack">팩</label>
        </div>
    </fieldset>
    <fieldset>
        <legend>탕전료</legend>
        <label for="produce">조제</label>
        <input type="number" name="produce" id="produce" value="10000" readonly>원<br>
        <label for="boil">탕전</label>
        <input type="number" name="boil" id="boil" value="10000" readonly>원<br>
        <label for="wrap">포장</label>
        <input type="number" name="wrap" id="wrap" value="10000" readonly>원
    </fieldset>
    <fieldset>
        <legend>탕전금액</legend>
        <input type="number" name="price" id="price" value="25400" readonly>
    </fieldset>
    <button type="submit">처방하기</button>
</form>

django_app/templates/index.html
{% extends 'layout/base.html' %}

{% block content %}
<ul>
    <li><a href="{% url "tang:recipe_list" %}">탕전주문</a></li>
    <li><a href="">약속처방주문</a></li>
</ul>    
{% endblock %}

django_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NEW MODERNLAB</title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
</head>
<body>
    <header>
        <h1>New ModernLab</h1>
        <div><small>{{ user.name|default:'Guest' }}</small></div>
        <nav>
            <a href="{% url "index" %}"><small>Home</small></a>
            {% if user.is_anonymous %}
                <a href="{% url 'login' %}"><small>Log in</small></a>
                <a href="{% url 'signup' %}"><small>Sing up</small></a>
            {% elif user.is_authenticated %}
                <a href=""><small>Cart</small></a>
                <a href=""><small>History</small></a>
                <a href="{% url 'logout' %}"><small>Log out</small></a>
            {% endif %}
        </nav>
    </header>

    {% include 'layout/messages.html' %}

    {% block content %}
    {% endblock content %}
</body>
</html>

django_app/templates/layout/base_form.html
{% if title %}
    <h4>{{ title }}</h4>
{% endif %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

django_app/templates/layout/messages.html
{% if messages %}
    <ul class="messages" style="list-style-type: none;">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <mark>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message|safe }}
            </mark>
        </li>
        {% endfor %}
    </ul>
{% endif %}

<script>
    var message = document.getElementsByClassName("messages")[0];
    setTimeout(function (){message.style.display="none"}, 5000);
</script>

django_app/templates/order_list.html
<h2>주문목록</h2>
날짜별 검색
환자명 검색

django_app/templates/tang/herb_detail.html
<a href="{% url 'tang:herb_list' %}">목록으로</a>

{{ herb.name }}: g당 {{ herb.price }}원
{% comment %} if condition request.user is admin {% endcomment %}
{% if request.user.is_superuser %}
    <br>
    너는 관리자니 알려주마<br>
    {{ herb.buy_unit }}g당 매입가격: {{ herb.buy_price }}원(마진율: {{ herb.margin}}%)
{% endif %}

django_app/templates/tang/herb_list.html
<h2>약재 목록</h2>
<a href="{% url 'tang:recipe_list' %}">처방 목록 보기</a>
<ul>
{% for herb in herb_list %}
    <li><a href="{% url 'tang:herb_detail' herb.slug %}">{{ herb.name }}</a></li>
{% endfor %}
</ul>

django_app/templates/tang/recipe_detail.html
<a href="{% url 'tang:recipe_list' %}">목록으로</a>


<h2>{{ recipe.name }} 처방구성</h2>

<ul>
{% for recipeherb in recipe.recipeherb_set.all %}
    <li>{{ recipeherb }}</li>
{% endfor %}
</ul>

django_app/templates/tang/recipe_list.html
<h2>처방 목록</h2>
<a href="{% url 'tang:herb_list' %}">약재 목록 보기</a>
<ul>
{% for recipe in recipe_list %}
    <li><a href="{% url 'tang:recipe_detail' recipe.slug %}">{{ recipe.name }}</a></li>
{% endfor %}
</ul>